Feature/news reader
dianavintila/NewsReader pull request #1
Opened 2021-07-05 05:32 UTC by dianavintila

2021-07-05 12:20 UTC, Misca requested changes
almost there

2021-07-05 12:20 UTC, Misca commented on app/src/main/java/com/dianavintila/newsreader/ui/feature/adapter/ArticleAdapter.java
> +    public static final String TITLE = "titlu";
let's remove all these constants and move them to the class that needs them, to NewsItemDetails; also let's never use any language besides english in code ever again

2021-07-05 12:20 UTC, Misca commented on app/src/main/java/com/dianavintila/newsreader/ui/feature/adapter/ArticleAdapter.java
> +        holder.itemView.setOnClickListener(v -> {
we should not handle clicks (have logic, navigation...) inside adapters, instead make this click go into the view model and publish an event for the fragment handle this with a navigator

2021-07-05 12:20 UTC, Misca commented on app/src/main/java/com/dianavintila/newsreader/ui/launch/NewsItemDetails.java
> +public class NewsItemDetails extends AppCompatActivity {
Let's rename this to NewsItemDetailsActivity so that we have the same naming convention

2021-07-05 12:20 UTC, Misca commented on app/src/main/java/com/dianavintila/newsreader/ui/feature/adapter/ArticleAdapter.java
> +        holder.itemView.setOnClickListener(v -> {
use a handler interface that receives the item click trough a bind

2021-07-05 12:20 UTC, Misca commented on data/src/main/java/com/dianavintila/data/features/news/local/ArticleEntity.java
> +    public String urlImage;
let's make these fields:
- final so that the states for this class will not change (besides the id, that one might need to stay non-final for room to work)
- let's add a constructor for them

2021-07-05 12:20 UTC, Misca commented on data/src/main/java/com/dianavintila/data/features/news/local/ArticleEntity.java
> +    public Integer getId() {
let's remove all the getters, we have the final fields public

2021-07-05 12:20 UTC, Misca commented on data/src/main/java/com/dianavintila/data/features/news/local/NewsLocalDataStore.java
> +public class NewsLocalDataStore {
let's make this class look better, auto-arrange it, we have at times there's no lines between methods, at times there are several

2021-07-05 18:19 UTC, dianavintila commented on app/src/main/java/com/dianavintila/newsreader/ui/feature/adapter/ArticleAdapter.java
> +    public static final String TITLE = "titlu";
done 👍

2021-07-05 18:45 UTC, dianavintila commented on data/src/main/java/com/dianavintila/data/features/news/local/ArticleEntity.java
> +    public String urlImage;
I understood what I did wrong and I changed :)

2021-07-05 18:46 UTC, dianavintila commented on data/src/main/java/com/dianavintila/data/features/news/local/ArticleEntity.java
> +    public Integer getId() {
done :)

2021-07-05 18:52 UTC, dianavintila commented on data/src/main/java/com/dianavintila/data/features/news/local/NewsLocalDataStore.java
> +public class NewsLocalDataStore {
done :)

2021-07-07 06:36 UTC, Misca approved these changes
Good job, Diana! 👍

2021-07-07 06:37 UTC, merged